version: '3.7'

services:
  web:
    restart: always
    build: .
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    links:
      - "db"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - ./.env.db
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

volumes:
  postgres_data:

