"""empty message

Revision ID: 46e5f0e29cb8
Revises: 9a2cb610f937
Create Date: 2021-01-02 05:56:20.073795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e5f0e29cb8'
down_revision = '9a2cb610f937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'team_tasks', ['task_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_tasks', type_='unique')
    # ### end Alembic commands ###
