"""empty message

Revision ID: 56a7ce0a0d68
Revises: a9ee009beb12
Create Date: 2020-12-20 06:34:45.832125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a7ce0a0d68'
down_revision = 'a9ee009beb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_role_name', sa.String(length=64), nullable=True),
    sa.Column('default_role', sa.Boolean(), nullable=True),
    sa.Column('team_permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_role_name')
    )
    op.create_index(op.f('ix_team_roles_default_role'), 'team_roles', ['default_role'], unique=False)
    op.add_column('team_members', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team_members', 'team_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_column('team_members', 'role_id')
    op.drop_index(op.f('ix_team_roles_default_role'), table_name='team_roles')
    op.drop_table('team_roles')
    # ### end Alembic commands ###
