"""empty message

Revision ID: 9a2cb610f937
Revises: 3f8f18ba58ab
Create Date: 2020-12-30 23:17:05.668393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2cb610f937'
down_revision = '3f8f18ba58ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_team_task', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_team_task')
    # ### end Alembic commands ###
