"""empty message

Revision ID: cbf1031bcfa5
Revises: 
Create Date: 2020-12-13 02:01:53.303937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf1031bcfa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default_role', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('role_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_roles_default_role'), 'roles', ['default_role'], unique=False)
    op.drop_index('ix_roles_default', table_name='roles')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['role_name'])
    op.drop_column('roles', 'default')
    op.drop_column('roles', 'name')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('roles', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    op.drop_index(op.f('ix_roles_default_role'), table_name='roles')
    op.drop_column('roles', 'role_name')
    op.drop_column('roles', 'default_role')
    # ### end Alembic commands ###
